spring:
  application:
    name: museio
  profiles:
    active: ${ENV}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
server:
  error:
    include-message: always
app:
  jwt:
    secret: ${JWT_SECRET}
    token-expiration: ${JWT_TOKEN_EXPIRATION:86400000} # 1 day in milliseconds
    auth-redirect-uri: ${AUTH_REDIRECT_URI}/auth/callback?id=